export default {
  message: {
    navs: 'Current',
    login: {
      title: 'Tunnel Management System Login',
      usernamePlaceholder: 'Please enter username',
      passwordPlaceholder: 'Please enter password',
      loginBtn: 'Login',
      success: 'Login Successful',
      fail: 'Login Failed',
    },
    common: {
      searchPlaceholder: 'Please enter search info',
      searchBtn: 'Search',
      addBtn: 'Add',
      editBtn: 'Edit',
      deleteBtn: 'Delete',
      operation: 'Actions',
      total: 'Total {total} items',
      status: 'Status',
      remark: 'Remark',
      confirm: 'Confirm',
      cancel: 'Cancel',
    },
    table: {
      username: 'Username',
      phone: 'Phone',
      permission: 'Permission',
      statusNormal: 'Normal',
      statusAbnormal: 'Abnormal',
      projectName: 'Project Name',
      projectCode: 'Project Code',
      projectMoney: 'Budget',
      projectAddress: 'Address',
      duration: 'Duration (Mo)',
      startTime: 'Start Time',
      endTime: 'End Time',
      tunnelCount: 'Tunnel Count',
      projectStatus: 'Status',
      underConstruction: 'In Progress',
      completed: 'Completed',
    },
  },
}
