export default {
  message: {
    navs: '現在',
    login: {
      title: 'トンネル管理システムログイン',
      usernamePlaceholder: 'ユーザー名を入力してください',
      passwordPlaceholder: 'パスワードを入力してください',
      loginBtn: 'ログイン',
      success: 'ログイン成功',
      fail: 'ログイン失敗',
    },
    common: {
      searchPlaceholder: '検索情報を入力してください',
      searchBtn: '検索',
      addBtn: '追加',
      editBtn: '編集',
      deleteBtn: '削除',
      operation: '操作',
      total: '合計 {total} 件',
      status: 'ステータス',
      remark: '備考',
      confirm: '確認',
      cancel: 'キャンセル',
    },
    table: {
      username: 'ユーザー名',
      phone: '電話番号',
      permission: '権限',
      statusNormal: '正常',
      statusAbnormal: '異常',
      projectName: 'プロジェクト名',
      projectCode: 'プロジェクトコード',
      projectMoney: '金額',
      projectAddress: '住所',
      duration: '工期(月)',
      startTime: '開始時間',
      endTime: '終了時間',
      tunnelCount: 'トンネル数',
      projectStatus: 'プロジェクト状態',
      underConstruction: '施工中',
      completed: '完了',
    },
  },
}
