export default {
  message: {
    navs: '当前',
    login: {
      title: '隧道后台管理系统登陆',
      usernamePlaceholder: '请输入用户名',
      passwordPlaceholder: '请输入密码',
      loginBtn: '登陆',
      success: '登录成功',
      fail: '登录失败',
    },
    common: {
      searchPlaceholder: '请输入要搜索的信息',
      searchBtn: '查询',
      addBtn: '添加',
      editBtn: '编辑',
      deleteBtn: '删除',
      operation: '操作',
      total: '共 {total} 条',
      status: '状态',
      remark: '备注',
      confirm: '确定',
      cancel: '取消',
    },
    table: {
      username: '用户名称',
      phone: '手机号码',
      permission: '权限',
      statusNormal: '正常',
      statusAbnormal: '异常',
      projectName: '项目名称',
      projectCode: '项目编码',
      projectMoney: '项目金额',
      projectAddress: '项目地址',
      duration: '工期(月)',
      startTime: '开工时间',
      endTime: '结束时间',
      tunnelCount: '隧道数量',
      projectStatus: '项目状态',
      underConstruction: '施工中',
      completed: '已完成',
    },
  },
}
